[13.0][FIX] dms: Set res_mimetype correctly in files
OCA/dms pull request #131
Opened 2021-08-20 11:04 UTC by victoralmau

Set `res_mimetype` correctly in files.

Please @Yajo and @pedrobaeza can you review it?

@Tecnativa TT30685

2021-08-20 14:18 UTC, pedrobaeza requested changes
I'm not sure we really need this, as this is very partial, but deploy properly a library that detects all the possible mimetypes instead of the limited implementation inside Odoo. Please check this code:

https://github.com/odoo/odoo/blob/c5a22a122eccd18247280a941efd2c96935c43d6/odoo/tools/mimetypes.py#L165-L179

Try in your local to put such library to see if it's detected properly, and if so we should:

- Add in base Doodba such library
- Put in the README in the installation section the recommendation to install the library.

2021-08-23 07:11 UTC, Yajo requested changes
As @pedrobaeza said, the first thing to try is to install those libraries and see if the problem goes away automatically. If that happens, close this.

Otherwise, a couple of code comments below.

2021-08-23 07:11 UTC, Yajo commented on dms/models/dms_file.py
> +        """ Similar to addons/base/models/ir_attachment.py#L232 """
This comment says nothing. And the line number can change. Please add a proper docstring and, if you need to refer to another resource, add a permalink.

2021-08-23 07:11 UTC, Yajo commented on dms/models/dms_file.py
> +                )
IIUC, you're trying to get the mimetype from the file name and, later, from the file contents.

IMHO it should be the opposite. The contents are usually more reliable than the file extension to know the kind of file you have.

2021-08-23 11:28 UTC, victoralmau commented
I tested locally to add the `python-magic` library and this changes will not be necessary because the `res_mimetype` field will be defined correctly.

Now the question is, do we add it as a dependency in the manifest or do we suggest its installation in the readme file and skip the parts of the test that are necessary if the library is not added?

Let's not forget that this happened because the `res_mimetype` field for `.mp4` files was not defined correctly.

2021-08-23 11:56 UTC, pedrobaeza commented
See my previous comment in https://github.com/OCA/dms/pull/131#pullrequestreview-735078892

2021-08-23 14:32 UTC, victoralmau commented
Changes done.
If everything is correct, do we add the `python-magic` library to https://github.com/Tecnativa/doodba or is it optional?

2021-08-23 16:24 UTC, pedrobaeza commented
> If everything is correct, do we add the `python-magic` library to https://github.com/Tecnativa/doodba or is it optional?

IMO we should add it for all, but meanwhile we can add it to current instances through the regular way. cc @Yajo

2021-08-23 16:26 UTC, pedrobaeza commented on dms/readme/INSTALL.rst
> +types and file preview.
```suggestion
`python-magic` library is recommended to be installed for having whole support
to get proper file types and file preview.
```

2021-08-24 06:17 UTC, pedrobaeza approved these changes

2021-08-24 06:44 UTC, Yajo approved these changes

2021-08-24 06:44 UTC, Yajo commented on dms/tests/test_file.py
> +            self.skipTest("Without python-magic library installed")
FTR there's a decorator for this: https://docs.python.org/3/library/unittest.html#unittest.skipIf

However it's OK as it is 😊

2021-08-24 06:44 UTC, Yajo commented
/ocabot merge patch

2021-08-24 08:26 UTC, Yajo commented
Failed due to https://github.com/odoo/odoo/pull/75387.

2021-08-24 12:59 UTC, rvalyi commented
Hello @Yajo, you could use https://github.com/OCA/l10n-brazil/pull/1587/commits/d43e0eb3329a8116628259a1b6f5ec556e59efb5 
(see https://odoo-community.org/groups/contributors-15/contributors-206982?mode=date&date_begin=2021-08-01&date_end=2021-09-01 )
to workarround the issue meanwhile if you want. That being said it seems Odoo SA is moving forward with this issue so may be waiting they fix it is an option.

2021-09-03 08:16 UTC, pedrobaeza commented
/ocabot merge patch

It can be fw-port it to v14 as well

2021-09-03 08:29 UTC, merged