[14.0][FIX] dms: Set res_mimetype correctly in files
OCA/dms pull request #133
Opened 2021-09-03 10:30 UTC by victoralmau

FWP from 13.0: https://github.com/OCA/dms/pull/131

Set `res_mimetype` correctly in files.

Please @Yajo and @pedrobaeza can you review it?

@Tecnativa TT31461

2021-09-03 10:31 UTC, pedrobaeza approved these changes
If CIs go green

2021-09-15 11:20 UTC, victoralmau commented
It's ready to merge right?

2021-09-15 11:25 UTC, Yajo requested changes
Just one tiny detail.

2021-09-15 11:25 UTC, Yajo commented on dms/readme/INSTALL.rst
> +`python-magic` library is recommended to be installed for having whole support
```suggestion
``python-magic`` library is recommended to be installed for having whole support
```

2021-09-15 11:33 UTC, Yajo approved these changes

2021-09-15 11:33 UTC, Yajo commented
/ocabot merge patch

2021-09-15 11:55 UTC, merged