[14.0][FIX] dms: Fix test portal test
OCA/dms pull request #200
Opened 2022-09-05 11:54 UTC by victoralmau

Avoid the error if an attachment to a partner has been created after installing dms.

Steps to reproduce the error:
- Install `dms`
- Install `l10n_en_aeat`
- Run `dms` tests

Please @pedrobaeza could you review it?

@Tecnativa

2022-09-05 12:41 UTC, pedrobaeza requested changes

2022-09-05 12:41 UTC, pedrobaeza commented on dms/tests/test_portal.py
> +        storage = self.env.ref("dms.storage_attachment_demo").copy(
Don't use demo data

2022-09-05 12:41 UTC, pedrobaeza commented on dms/tests/test_storage_attachment.py
> +        self.env.ref("base.group_private_addresses").write(
Why this? I don't think it's needed.

2022-09-05 12:41 UTC, pedrobaeza commented on dms/tests/test_portal.py
>          self.partner = self.env.ref("base.partner_demo_portal")
Don't use demo data

2022-09-05 16:01 UTC, victoralmau commented on dms/tests/test_portal.py
>          self.partner = self.env.ref("base.partner_demo_portal")
Almost all tests are based on demo data and users with specific permissions, I think this should be changed, what do you think?

2022-09-05 16:14 UTC, pedrobaeza commented on dms/tests/test_portal.py
>          self.partner = self.env.ref("base.partner_demo_portal")
Ok

2022-09-06 08:00 UTC, victoralmau commented
Changes done and code refactor.

2022-09-06 12:46 UTC, pedrobaeza approved these changes

2022-09-06 13:06 UTC, chienandalu approved these changes

2022-09-06 13:07 UTC, pedrobaeza commented
/ocabot merge patch

2022-09-06 13:13 UTC, merged