[IMP] dms: Portal
OCA/dms pull request #22
Opened 2020-10-05 08:52 UTC by victoralmau

**Portal functionallity**

Users with portal access view link to "Documents"
In Documents show all "root" directories with explicit access to portal and files it.

This new feature use Access Group field in directories and files. It's neccessary "read" permission to show in portal.

If directory have access group to portal, by default, all subdirectories too, but if "not inherit groups" field not selected dissapear.

Add too "Share" link to Directories and Files to show it with custom link

@Tecnativa TT25647

2020-10-05 10:29 UTC, etobella requested changes
The download button did not work on portal. Great Addition :wink:

2020-10-05 11:56 UTC, victoralmau commented
> The download button did not work on portal. Great Addition wink

Thanks, updated and work fine now

2020-10-05 20:09 UTC, ernestotejeda reviewed
Great job, thanks. 
I found only two issues: review 'Sort by and filter by' functionalities.

![Peek 2020-10-05 15-58](https://user-images.githubusercontent.com/38267832/95126759-eceb6900-0724-11eb-81dc-af50e9d1990f.gif)

2020-10-05 20:44 UTC, ernestotejeda commented on dms/models/directory.py
> +        return "{}?{}".format(url, url_encode(params))
Why not to override _compute_access_url method instead? 
simila to this: https://github.com/OCA/rma/blob/12.0/rma/models/rma.py#L414

2020-10-06 12:24 UTC, victoralmau commented
> Great job, thanks.
> I found only two issues: review 'Sort by and filter by' functionalities.
> 
> ![Peek 2020-10-05 15-58](https://user-images.githubusercontent.com/38267832/95126759-eceb6900-0724-11eb-81dc-af50e9d1990f.gif)

Thanks, "filter by" removed now (because in searchbar it's possible to select only name) and sort by solved.

2020-10-06 14:54 UTC, jarroyomorales commented
Hi @victoralmau! Tested it on runbot and works as expected! The only thing I'm wondering is if it is okay to put it on the base module or if we should create a `dms_portal` module, what do you think?

2020-10-06 14:57 UTC, pedrobaeza commented
@jarroyomorales portal functionality is in base for all the core modules (`sale`, `account`, etc), so it's reasonable to have it also bundled together, and the code addition is not too much.

2020-10-06 14:59 UTC, victoralmau commented
> Hi @victoralmau! Tested it on runbot and works as expected! The only thing I'm wondering is if it is okay to put it on the base module or if we should create a `dms_portal` module, what do you think?

Thanks! I think that it's necessary to include in base module because "portal feature" haven't dependencies. Portal feature only work if you like.

2020-10-06 15:08 UTC, jarroyomorales commented
@victoralmau @pedrobaeza Okay then!

2020-10-06 20:50 UTC, ernestotejeda reviewed
Now everything works very fine.
But, ... I'm not quite sure how it is done to determine what a portal user should and shouldn't see. Anyway, I think there should be an access rule for portal users so that they can only see the documents that they are follower of? What do you think?

2020-10-07 06:10 UTC, victoralmau commented
> Now everything works very fine.
> But, ... I'm not quite sure how it is done to determine what a portal user should and shouldn't see. Anyway, I think there should be an access rule for portal users so that they can only see the documents that they are follower of? What do you think?

Thank you for review and comment about it.
In DMS, ACLS are override in dms_security_mixin.py, the idea is create dms_access_group and apply to directories (this groups override ACLs) and simplify "rule access" rewriting ACLs.
Use followers is a good idea and will allow create a general rule about portal BUT it's more difficult to aplly (in a directory for example) if compare it with access group that contains some groups and explicit users. 
Exist a issue https://github.com/OCA/dms/issues/23 about ACL system modify.

2020-10-07 12:30 UTC, ernestotejeda approved these changes
Sorry, and thanks for the clarification.
I was confused because I thought that the demo 'DMS Access Groups' (dms.access.group) named 'Admin' and 'Demo' were referring to the Admin and demo users, but I see that they are not. But, I already saw that 'Admin' includes the admin and demo users, and 'Demo' includes the portal user.

2020-10-07 14:20 UTC, pedrobaeza requested changes
Latest changes and we can go on!

2020-10-07 14:20 UTC, pedrobaeza commented on dms/controllers/portal.py
> +            elif not item_sudo.access_token and model == "dms.file":
```suggestion
            elif model == "dms.file":
```

2020-10-07 14:20 UTC, pedrobaeza commented on dms/controllers/portal.py
> +            elif not item_sudo.access_token and model == "dms.file":
I think anyways that there should be 2 separate methods for this, as the code gets ugly with no real gain having together (on contrary, you need to constantly check `model == "dms.file"`). What do you think?

2020-10-07 14:20 UTC, pedrobaeza commented on dms/models/directory.py
> +    partner_id = fields.Many2one(comodel_name="res.partner", store=False)
This can be already removed as it's merged in 12.0

2020-10-07 14:20 UTC, pedrobaeza commented on dms/models/dms_file.py
> +    partner_id = fields.Many2one(comodel_name="res.partner", store=False)
To be removed

2020-10-07 14:20 UTC, pedrobaeza commented on dms/readme/DESCRIPTION.rst
> +This module add portal functionallity to directories and files (related to access group that allow it to read portal group)
```suggestion

This module adds portal functionality for directories and files for allowed users, both portal or internal users. You can get as well a tokenized link from a directory or a file for sharing it with any anonymous user.
```

2020-10-07 14:20 UTC, pedrobaeza commented on dms/readme/ROADMAP.rst
> +- Tour test to portal
Isn't this finally done?

2020-10-07 14:20 UTC, pedrobaeza commented on dms/readme/USAGE.rst
> +The best way to active portal is create Access group that allow read some users (or groups) and apply to some directories
```suggestion
Portal functionality
~~~~~~~~~~~~~~~~~~~~

You can add any portal user to DMS access groups, and then allow that group in directories, so they will see in the portal such directories and their files.

Another possibility is to click on "Share" button inside a directory or a file for obtaining a tokenized link for single access to that resource, no matter if logged or not.
```

2020-10-07 14:20 UTC, pedrobaeza commented on dms/security/ir.model.access.csv
> +
This file shouldn't contain any empty line. Please remove all.

2020-10-07 14:20 UTC, pedrobaeza commented on dms/tests/__init__.py
> +"""
Remove this that is avoiding to execute the rest of the tests

2020-10-07 14:20 UTC, pedrobaeza commented on dms/views/assets.xml
> +    <template id="dms_frontend_demo" inherit_id="web.assets_frontend">
Please include this as demo data, as there's not too much sense to load this for production deployments.

2020-10-07 14:40 UTC, victoralmau commented on dms/controllers/portal.py
> +            elif not item_sudo.access_token and model == "dms.file":
All changes apply, thanks!
About this suggestion now function contains some custom logic, separated now in 2 similar functions (every function with your model).

Maybe a solution to remove all this logic is describe in https://github.com/OCA/dms/issues/23

2020-10-07 14:43 UTC, ernestotejeda commented
Fix the commit name

2020-10-07 14:51 UTC, pedrobaeza commented on dms/readme/DESCRIPTION.rst
> +This module adds portal functionality for directories and files for allowed users, both portal or internal users. You can get as well a tokenized link from a directory or a file for sharing it with a
For proper paragraph recognition in RST, you must leave an empty blank line in between, so please reformat this properly.

2020-10-07 14:51 UTC, pedrobaeza commented on dms/readme/USAGE.rst
> +You can add any portal user to DMS access groups, and then allow that group in directories, so they will see in the portal such directories and their files.
Missing empty lines for paragraphs (in both).

2020-10-07 15:10 UTC, pedrobaeza approved these changes

2020-10-07 15:11 UTC, pedrobaeza commented
@etobella can you change your review?

2020-10-08 09:42 UTC, pedrobaeza commented
As @etobella doesn't answer, but his comments are honored, let's continue with the merge:

/ocabot merge major

2020-10-08 10:00 UTC, merged

2020-10-08 20:04 UTC, mileo commented
Nice work!