[16.0][MIG]dms_attachment_link: port to 16.0 version
OCA/dms pull request #311
Opened 2024-03-12 22:40 UTC by DemchukM

Migrate dms_attachment_link module from Odoo 15.0 to Odoo 16.0

2024-03-13 19:41 UTC, pedrobaeza commented
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

2024-07-06 16:50 UTC, Aldeigja commented
> Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0.

@pedrobaeza we have updated PR with the commit history preserved.
Please check if this is good enough now for merging.
Thanks.

2024-07-07 18:52 UTC, angelinaanaki approved these changes
Code LGTM

2024-07-08 06:46 UTC, pedrobaeza commented
Formally seems OK, now reviewers should check the migration itself.

/ocabot migration dms_attachment_link

2024-07-10 15:56 UTC, victoralmau requested changes

2024-07-10 15:56 UTC, victoralmau commented on dms_attachment_link/models/ir_attachment.py
> +        return attachments
Why is this change necessary? The `_compute_datas()` method already takes care of it (or should).

2024-07-11 18:01 UTC, hoangtrann approved these changes
In general code LGTM, agree with @victoralmau that extending `_compute_datas()` isn't neccessary

2024-07-11 18:01 UTC, hoangtrann commented on dms_attachment_link/models/ir_attachment.py
> +        """Get the contents of the attachment directly from the DMS fiel."""
```suggestion
        """Get the contents of the attachment directly from the DMS file."""
```

2024-07-27 09:16 UTC, mostafabarmshory commented
Dear all, Would you fix and merge with the main 16.0 branch. 
tx

2024-09-25 04:41 UTC, mostafabarmshory commented
@DemchukM 

Seams unit testes fail. This prevent the merge process?!

2024-09-25 14:45 UTC, victoralmau requested changes
Code review OK.

The changes from commit _[16.0][FIX]dms_attachment_link: refactoring code_ add them to _[16.0][MIG]dms_attachment_link: port to 16.0 version_

The errors in tests will already be solved when you run it again (it was related to https://github.com/OCA/oca-ci/pull/78).

2024-09-25 15:41 UTC, mostafabarmshory commented
The branch 17.0 dose not contain this module. What the problem is?

2024-09-27 08:54 UTC, victoralmau commented
> The branch 17.0 dose not contain this module. What the problem is?

The 17.0 branch does not have this module because it has not been migrated. If you want to migrate it you can do it (for example when this migration is finished and it is merged in v16).

2024-10-01 15:26 UTC, victoralmau commented
Superseed by https://github.com/OCA/dms/pull/371

2024-10-02 07:23 UTC, closed without merging