[17.0][MIG] dms_storage: Migration to 17.0
OCA/dms pull request #362
Opened 2024-08-27 06:12 UTC by BernatObrador

2024-08-27 10:14 UTC, peluko00 requested changes

2024-08-27 10:14 UTC, peluko00 commented on dms_storage/models/dms_file.py
> +    storage_path = fields.Char(invisible=True)
Invisible not affect in model only in view. Maybe is much better to put readonly field and invisible it in view

2024-08-27 12:05 UTC, peluko00 approved these changes
LGTM, tested in runboat

2024-08-29 08:49 UTC, ppyczko approved these changes
LGTM

2024-09-06 06:06 UTC, BernatObrador commented
@pedrobaeza Is this ready to merge?

2024-09-06 06:09 UTC, pedrobaeza commented
/ocabot migration dms_storage

@etobella please confirm

2024-09-06 17:10 UTC, etobella approved these changes
Code Review

2024-09-06 17:19 UTC, pedrobaeza commented
/ocabot merge nobump

2024-09-06 18:17 UTC, pedrobaeza commented
/ocabot merge nobump

2024-09-06 18:22 UTC, merged