[14.0][FIX] dms: Improve _get_share_url() function to add share_token parameter
OCA/dms pull request #79
Opened 2021-05-24 08:24 UTC by victoralmau

FWP from 13.0: https://github.com/OCA/dms/pull/78

Improve `_get_share_url()` function to add share_token parameter (according to https://github.com/odoo/odoo/commit/a55f125f5420797a9378925da5626e43d002b9b0).

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT29820

2021-05-24 08:25 UTC, pedrobaeza approved these changes

2021-05-24 08:25 UTC, pedrobaeza commented
One question: shouldn't be the token then populated only if the new argument is true?

2021-05-24 08:26 UTC, chienandalu approved these changes

2021-05-24 08:29 UTC, victoralmau commented
> One question: shouldn't be the token then populated only if the new argument is true?

IMO is not necessary because actually code use always `access_token` (similar to https://github.com/odoo/odoo/commit/a55f125f5420797a9378925da5626e43d002b9b0#diff-b90ce1ef695264f5890e01458a99eb2b7ab9679df4cfdbec5a0d4c3f156f9e67R54)

2021-05-24 08:33 UTC, pedrobaeza requested changes
That's not what I'm reading in the link you have passed me, so please follow the same steps as in sale:

- Gather params in the variables and then call to `encode_params`.
- Don't populate the access token if `share_token` is False.

2021-05-26 12:22 UTC, victoralmau commented
According to analysis related to `_get_share_url()` in https://github.com/OCA/contract/pull/680 and test share button, share link and button in mail, my conclusion is that `_get_share_url()` is not necessary (default functionality is correct in `dms` use case).

2021-05-31 15:29 UTC, victoralmau commented
It's not necessary now because these changes have apllied in https://github.com/OCA/dms/pull/93#event-4821233586

2021-05-31 15:30 UTC, closed without merging